### ISSUE TITLE
在deploy_helper.py中增加checker以及logger

### ISSUE THREAD

**Issue by Kaiser-Yang** [CMIPT/gcs-back-end#10]
增加`logger`系统，支持不同级别的日志。

增加`command_checker`，`command_checker`的大概要求如下：
* 接受三个个参数，分别代表状态码，信息，期望状态码（默认值0）
* 在`command_checker`中，判断状态码是否和期望状态码相同，当相同时不执行任何操作；当不同的时候通过日志系统打印`ERR`级别的日志，并通过`exit`退出，退出码为传入的状态码。
* 在增加了`command_checker`后，应该将类似`res = ... if res !=0 ...`的代码修改成调用`command_checker`并添加相应的`message`

**Comment by ajiankexx** [comment]
```python
res = os.system(f'sudo service {config.serviceName} stop && '
                            f'sudo rm /etc/init.d/{config.serviceName} && '
                            f'sudo systemctl daemon-reload')
            if res != 0:
                return res
```
在这段代码中，res!=0时没有输出任何内容，所以此时command_checker的message参数是不是可以设置为空。

**Comment by Kaiser-Yang** [comment]
> ```python
> res = os.system(f'sudo service {config.serviceName} stop && '
>                             f'sudo rm /etc/init.d/{config.serviceName} && '
>                             f'sudo systemctl daemon-reload')
>             if res != 0:
>                 return res
> ```
> 
> 在这段代码中，res!=0时没有输出任何内容，所以此时command_checker的message参数是不是可以设置为空。

你应该为其添加一个合理的`message`表明什么过程失败了。另外请从最新的`develop`进行更改，这段代码在新的提交中已经被删除了
